"""добавил колонки приоритетности и запланированной даты

Revision ID: 24e73bad9936
Revises: 
Create Date: 2021-03-15 18:56:42.979478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e73bad9936'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('scheduled_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'scheduled_date')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
