"""добавил колонку запланированной даты

Revision ID: 792caedaed7c
Revises: 994465b9c4c0
Create Date: 2021-03-16 19:13:51.580747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792caedaed7c'
down_revision = '994465b9c4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scheduled_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'scheduled_date')
    # ### end Alembic commands ###
