"""изменил значение по умолчанию в колонке даты задачи

Revision ID: 994465b9c4c0
Revises: 24e73bad9936
Create Date: 2021-03-16 19:11:01.573383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994465b9c4c0'
down_revision = '24e73bad9936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.drop_column('scheduled_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scheduled_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
